version: '3.9'

services:

  db:
    image: postgres:15.7-bullseye
    container_name: postgresql
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - /mnt/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
      PGDATA: /var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4:8.9
    container_name: pgadmin4
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 
      PGADMIN_DEFAULT_PASSWORD: 
    volumes:
      - /mnt/pgadmin:/var/lib/pgadmin
